import { PatientCase } from './types';

export const PATIENT_FATIMA: PatientCase = {
  id: 'PAT-DXB-2026-0892',
  mrn: 'DHA-892144-AE',
  name: 'Fatima Al-Mansoor',
  age: 48,
  gender: 'F',
  weightKg: 74.5,
  heightCm: 165,
  bmi: 27.4,
  scheduledTimeIso: new Date(Date.now() + 18 * 3600 * 1000).toISOString(),
  procedureName: 'Laparoscopic Cholecystectomy',
  cptCode: 'CPT 47562',
  invasivenessTier: 2,
  facility: 'Al Garhoud Day Surgery Center, Dubai (mock demo case)',
  surgeon: 'Dr. Tariq Al-Hashimi, FRCS',
  anesthesiologist: 'Dr. Mariam Ben-Salem, DESA (Consultant Anaesthetist)',
  asaStatus: 'ASA II',
  rcriClass: 'Class I (<0.4%)',
  stopBangScore: 2,
  swimLane: 'LANE_2_TELEPHONIC',
  phoneNumber: '+971 50 892 1440',
  preferredLanguage: 'ar',
  isPregnant: false,
  hasActiveInfection: false,
  airway: {
    mallampati: 'Class II',
    mouthOpeningCm: 4.5,
    thyromentalDistanceCm: 6.8,
    neckMobility: 'Full',
    dentition: 'Intact',
    riskTier: 'LOW',
  },
  medications: [
    {
      id: 'med-1',
      drugName: 'Semaglutide (Ozempic 1.0mg weekly)',
      category: 'GLP1',
      dosageSchedule: '1.0 mg SubQ Weekly',
      lastDoseHoursAgo: 180,
      requiredHoldHours: 168,
      status: 'CLEARED',
      guidelineBasis: 'ASA 2023 Consensus on Preoperative GLP-1 RA Management',
      clinicalAction: 'Hold window (180h > 168h required) met. Cleared for standard general anesthesia induction.',
      isWeekly: true,
    },
    {
      id: 'med-2',
      drugName: 'Lisinopril (20mg daily)',
      category: 'ACE_ARB',
      dosageSchedule: '20 mg Oral Daily',
      lastDoseHoursAgo: 22,
      requiredHoldHours: 24,
      status: 'HOLD_REQUIRED',
      guidelineBasis: 'Perioperative Vasoplegia & Refractory Hypotension Shield Protocol',
      clinicalAction: 'Hold morning dose on day of surgery. Administer IV fluid bolus pre-induction if SBP < 110 mmHg.',
    },
    {
      id: 'med-3',
      drugName: 'Rosuvastatin (10mg daily)',
      category: 'OTHER',
      dosageSchedule: '10 mg Oral Nightly',
      lastDoseHoursAgo: 14,
      requiredHoldHours: 0,
      status: 'CLEARED',
      guidelineBasis: 'ACC/AHA Guideline on Perioperative Cardiovascular Evaluation',
      clinicalAction: 'Continue uninterrupted through surgical stay.',
    },
  ],
  allergies: [
    {
      id: 'allergy-1',
      allergen: 'Sulfonamide Antibiotics',
      reaction: 'Maculopapular rash, fever',
      severity: 'MODERATE',
      category: 'MEDICATION',
      documentedDate: '2019-03-15',
    },
  ],
  vitals: [
    {
      timestamp: new Date(Date.now() - 3600000).toISOString(),
      systolicBp: 128,
      diastolicBp: 82,
      heartRate: 72,
      spo2: 98,
      temperatureC: 36.6,
      respiratoryRate: 14,
    },
    {
      timestamp: new Date(Date.now() - 86400000).toISOString(),
      systolicBp: 132,
      diastolicBp: 84,
      heartRate: 74,
      spo2: 97,
      temperatureC: 36.7,
      respiratoryRate: 16,
    },
  ],
  labs: [
    {
      id: 'lab-k',
      name: 'Potassium (Serum K+)',
      loinc: '2823-3',
      value: 3.2,
      unit: 'mEq/L',
      refLow: 3.5,
      refHigh: 5.1,
      status: 'BORDERLINE_LOW',
      directive: 'Oral KCl 20mEq on arrival; recheck POC K+ prior to induction.',
      provenance: {
        documentName: 'Al_Borg_DXB_Report_89214.pdf',
        page: 1,
        bbox: { ymin: 342, xmin: 68, ymax: 382, xmax: 530 },
        rawOcrText: 'Potassium (ISE Diluted) .......... 3.20 mEq/L [3.50 - 5.10] LOW - Verified by Auto-check DXB-LAB4',
        confidence: 0.994,
      },
    },
    {
      id: 'lab-na',
      name: 'Sodium (Serum Na+)',
      loinc: '2951-2',
      value: 139,
      unit: 'mEq/L',
      refLow: 135,
      refHigh: 145,
      status: 'NORMAL',
      directive: 'Normal electrolyte balance; standard maintenance fluids.',
      provenance: {
        documentName: 'Al_Borg_DXB_Report_89214.pdf',
        page: 1,
        bbox: { ymin: 298, xmin: 68, ymax: 338, xmax: 530 },
        rawOcrText: 'Sodium (ISE Diluted) ............. 139.0 mEq/L [135.0 - 145.0] Normal',
        confidence: 0.998,
      },
    },
    {
      id: 'lab-cl',
      name: 'Chloride (Serum Cl-)',
      loinc: '2075-0',
      value: 102,
      unit: 'mEq/L',
      refLow: 98,
      refHigh: 107,
      status: 'NORMAL',
      directive: 'Normal chloride range.',
      provenance: {
        documentName: 'Al_Borg_DXB_Report_89214.pdf',
        page: 1,
        bbox: { ymin: 386, xmin: 68, ymax: 426, xmax: 530 },
        rawOcrText: 'Chloride (ISE Diluted) ........... 102.0 mEq/L [98.0 - 107.0] Normal',
        confidence: 0.991,
      },
    },
    {
      id: 'lab-hco3',
      name: 'Bicarbonate (HCO3)',
      loinc: '1963-8',
      value: 24,
      unit: 'mEq/L',
      refLow: 22,
      refHigh: 29,
      status: 'NORMAL',
      directive: 'Normal acid-base reserve.',
      provenance: {
        documentName: 'Al_Borg_DXB_Report_89214.pdf',
        page: 1,
        bbox: { ymin: 430, xmin: 68, ymax: 470, xmax: 530 },
        rawOcrText: 'Carbon Dioxide / Bicarbonate ..... 24.0 mEq/L [22.0 - 29.0] Normal',
        confidence: 0.989,
      },
    },
    {
      id: 'lab-bun',
      name: 'Blood Urea Nitrogen (BUN)',
      loinc: '3094-0',
      value: 14,
      unit: 'mg/dL',
      refLow: 7,
      refHigh: 20,
      status: 'NORMAL',
      directive: 'Normal renal perfusion marker.',
      provenance: {
        documentName: 'Al_Borg_DXB_Report_89214.pdf',
        page: 1,
        bbox: { ymin: 474, xmin: 68, ymax: 514, xmax: 530 },
        rawOcrText: 'BUN (Urease/GLDH) ................ 14.0 mg/dL [7.0 - 20.0] Normal',
        confidence: 0.996,
      },
    },
    {
      id: 'lab-cr',
      name: 'Serum Creatinine',
      loinc: '2160-0',
      value: 0.82,
      unit: 'mg/dL',
      refLow: 0.55,
      refHigh: 1.02,
      status: 'NORMAL',
      directive: 'Normal baseline renal clearance (eGFR > 90 mL/min/1.73m2).',
      provenance: {
        documentName: 'Al_Borg_DXB_Report_89214.pdf',
        page: 1,
        bbox: { ymin: 518, xmin: 68, ymax: 558, xmax: 530 },
        rawOcrText: 'Creatinine Enzymatic ............. 0.82 mg/dL [0.55 - 1.02] Normal',
        confidence: 0.997,
      },
    },
    {
      id: 'lab-glu',
      name: 'Fasting Blood Glucose',
      loinc: '1558-6',
      value: 112,
      unit: 'mg/dL',
      refLow: 70,
      refHigh: 99,
      status: 'BORDERLINE_HIGH',
      directive: 'Check POC glucose on arrival. Target perioperative glycemia 140-180 mg/dL.',
      provenance: {
        documentName: 'Al_Borg_DXB_Report_89214.pdf',
        page: 1,
        bbox: { ymin: 562, xmin: 68, ymax: 602, xmax: 530 },
        rawOcrText: 'Glucose Fasting (Hexokinase) ..... 112 mg/dL [70 - 99] HIGH',
        confidence: 0.992,
      },
    },
    {
      id: 'lab-hba1c',
      name: 'Hemoglobin A1c',
      loinc: '4548-4',
      value: 7.1,
      unit: '%',
      refLow: 4.0,
      refHigh: 5.7,
      status: 'BORDERLINE_HIGH',
      directive: 'Optimal elective surgical control (<8.0% threshold satisfied).',
      provenance: {
        documentName: 'Al_Borg_DXB_Report_89214.pdf',
        page: 2,
        bbox: { ymin: 120, xmin: 68, ymax: 160, xmax: 530 },
        rawOcrText: 'HbA1c (HPLC Tosoh G8) ............ 7.1 % [4.0 - 5.7] Managed Diabetes',
        confidence: 0.998,
      },
    },
    {
      id: 'lab-wbc',
      name: 'White Blood Cell Count',
      loinc: '6690-2',
      value: 6.8,
      unit: 'x10³/µL',
      refLow: 4.0,
      refHigh: 11.0,
      status: 'NORMAL',
      directive: 'Normal leukocyte count; no signs of active infection.',
      provenance: {
        documentName: 'Al_Borg_DXB_Report_89214.pdf',
        page: 2,
        bbox: { ymin: 220, xmin: 68, ymax: 260, xmax: 530 },
        rawOcrText: 'WBC .............................. 6.8 x10^3/uL [4.0 - 11.0] Normal',
        confidence: 0.995,
      },
    },
    {
      id: 'lab-hgb',
      name: 'Hemoglobin (Hb)',
      loinc: '718-7',
      value: 13.1,
      unit: 'g/dL',
      refLow: 12.0,
      refHigh: 15.5,
      status: 'NORMAL',
      directive: 'Adequate red cell reserve; blood cross-match type & screen on file.',
      provenance: {
        documentName: 'Al_Borg_DXB_Report_89214.pdf',
        page: 2,
        bbox: { ymin: 264, xmin: 68, ymax: 304, xmax: 530 },
        rawOcrText: 'Hemoglobin (Photometric) ......... 13.1 g/dL [12.0 - 15.5] Normal',
        confidence: 0.996,
      },
    },
    {
      id: 'lab-hct',
      name: 'Hematocrit (Hct)',
      loinc: '4544-3',
      value: 39.4,
      unit: '%',
      refLow: 37.0,
      refHigh: 48.0,
      status: 'NORMAL',
      directive: 'Normal hematocrit.',
      provenance: {
        documentName: 'Al_Borg_DXB_Report_89214.pdf',
        page: 2,
        bbox: { ymin: 308, xmin: 68, ymax: 348, xmax: 530 },
        rawOcrText: 'Hematocrit ....................... 39.4 % [37.0 - 48.0] Normal',
        confidence: 0.991,
      },
    },
    {
      id: 'lab-plt',
      name: 'Platelet Count',
      loinc: '777-3',
      value: 248000,
      unit: '/µL',
      refLow: 150000,
      refHigh: 450000,
      status: 'NORMAL',
      directive: 'Platelet count safe for regional block or general anesthesia.',
      provenance: {
        documentName: 'Al_Borg_DXB_Report_89214.pdf',
        page: 2,
        bbox: { ymin: 352, xmin: 68, ymax: 392, xmax: 530 },
        rawOcrText: 'Platelet Count (Impedance) ....... 248,000 /uL [150,000 - 450,000] Normal',
        confidence: 0.999,
      },
    },
    {
      id: 'lab-inr',
      name: 'PT / INR (Prothrombin Time)',
      loinc: '6301-6',
      value: 1.02,
      unit: 'ratio',
      refLow: 0.85,
      refHigh: 1.15,
      status: 'NORMAL',
      directive: 'Normal baseline coagulation cascade.',
      provenance: {
        documentName: 'Al_Borg_DXB_Report_89214.pdf',
        page: 2,
        bbox: { ymin: 440, xmin: 68, ymax: 480, xmax: 530 },
        rawOcrText: 'Prothrombin Time INR ............ 1.02 ratio [0.85 - 1.15] Normal',
        confidence: 0.997,
      },
    },
  ],
  overallStatus: 'AMBER_CONDITIONAL',
  primaryActionDirective: 'CONDITIONAL CLEARANCE: Oral KCl 20mEq on arrival + Hold morning Lisinopril (Vasoplegia Shield).',
};

export const PATIENT_RAJESH: PatientCase = {
  id: 'PAT-BLR-2026-4401',
  mrn: 'APL-440192-IN',
  name: 'Rajesh Sharma',
  age: 64,
  gender: 'M',
  weightKg: 88.0,
  heightCm: 172,
  bmi: 29.7,
  scheduledTimeIso: new Date(Date.now() + 48 * 3600 * 1000).toISOString(),
  procedureName: 'Total Knee Arthroplasty (Right TKA)',
  cptCode: 'CPT 27447',
  invasivenessTier: 3,
  facility: 'Apollo Specialty Hospital, Bannerghatta Road, Bangalore',
  surgeon: 'Prof. Dr. Vikramaditya Reddy, MS (Ortho), MCh',
  anesthesiologist: 'Dr. Sunita Deshmukh, MD, FICCM (Lead Anaesthesiologist)',
  asaStatus: 'ASA III',
  rcriClass: 'Class II (0.9%)',
  stopBangScore: 4,
  swimLane: 'LANE_3_IN_PERSON',
  phoneNumber: '+91 98450 44019',
  preferredLanguage: 'en',
  isPregnant: false,
  hasActiveInfection: false,
  airway: {
    mallampati: 'Class III',
    mouthOpeningCm: 3.8,
    thyromentalDistanceCm: 6.0,
    neckMobility: 'Restricted',
    dentition: 'Caps/Crowns',
    riskTier: 'MODERATE',
  },
  medications: [
    {
      id: 'med-r1',
      drugName: 'Apixaban (Eliquis 5mg BID)',
      category: 'DOAC',
      dosageSchedule: '5 mg Oral Twice Daily',
      lastDoseHoursAgo: 28,
      requiredHoldHours: 72,
      status: 'HARD_STOP',
      guidelineBasis: 'ASRA Coagulation Guidelines (2025) for Neuraxial Anesthesia',
      clinicalAction: 'HARD STOP: Active DOAC washout inadequate (28h elapsed vs 72h mandatory for spinal block). Postpone neuraxial technique or reschedule case.',
    },
    {
      id: 'med-r2',
      drugName: 'Metformin (500mg daily)',
      category: 'SGLT2I',
      dosageSchedule: '500 mg Oral Daily',
      lastDoseHoursAgo: 24,
      requiredHoldHours: 24,
      status: 'HOLD_REQUIRED',
      guidelineBasis: 'Perioperative Glycemic Safety Protocol',
      clinicalAction: 'Hold on morning of surgery; resume when oral intake is tolerated post-op.',
    },
    {
      id: 'med-r3',
      drugName: 'Amlodipine (5mg daily)',
      category: 'BETA_BLOCKER',
      dosageSchedule: '5 mg Oral Morning',
      lastDoseHoursAgo: 24,
      requiredHoldHours: 0,
      status: 'CLEARED',
      guidelineBasis: 'ACC/AHA Perioperative Blood Pressure Management',
      clinicalAction: 'Continue with sips of water on morning of surgery.',
    },
  ],
  allergies: [
    {
      id: 'allergy-r1',
      allergen: 'Penicillin',
      reaction: 'Urticaria, angioedema',
      severity: 'SEVERE',
      category: 'MEDICATION',
      documentedDate: '2010-08-22',
    },
    {
      id: 'allergy-r2',
      allergen: 'Iodinated Contrast',
      reaction: 'Mild nausea',
      severity: 'MILD',
      category: 'CONTRAST_DYE',
      documentedDate: '2023-01-10',
    },
  ],
  vitals: [
    {
      timestamp: new Date(Date.now() - 7200000).toISOString(),
      systolicBp: 142,
      diastolicBp: 90,
      heartRate: 78,
      spo2: 96,
      temperatureC: 36.9,
      respiratoryRate: 16,
    },
    {
      timestamp: new Date(Date.now() - 86400000).toISOString(),
      systolicBp: 138,
      diastolicBp: 88,
      heartRate: 76,
      spo2: 97,
      temperatureC: 36.8,
      respiratoryRate: 15,
    },
  ],
  labs: [
    {
      id: 'lab-r-hgb',
      name: 'Hemoglobin (Hb)',
      loinc: '718-7',
      value: 10.2,
      unit: 'g/dL',
      refLow: 13.0,
      refHigh: 17.5,
      status: 'BORDERLINE_LOW',
      directive: 'Borderline anemia for high-bleed orthopaedic case. Order 2 units packed RBC type & screen + Pre-op IV Iron assessment.',
      provenance: {
        documentName: 'Dr_Lal_BLR_Report_44019.pdf',
        page: 1,
        bbox: { ymin: 310, xmin: 68, ymax: 350, xmax: 530 },
        rawOcrText: 'HEMOGLOBIN, WHOLE BLOOD .......... 10.20 g/dL [13.00 - 17.50] LOW (Cyanmethemoglobin)',
        confidence: 0.993,
      },
    },
    {
      id: 'lab-r-hct',
      name: 'Hematocrit (Hct)',
      loinc: '4544-3',
      value: 31.2,
      unit: '%',
      refLow: 40.0,
      refHigh: 50.0,
      status: 'BORDERLINE_LOW',
      directive: 'Reduced hematocrit in setting of planned major arthroplasty.',
      provenance: {
        documentName: 'Dr_Lal_BLR_Report_44019.pdf',
        page: 1,
        bbox: { ymin: 354, xmin: 68, ymax: 394, xmax: 530 },
        rawOcrText: 'PCV / HEMATOCRIT ................. 31.20 % [40.00 - 50.00] LOW',
        confidence: 0.991,
      },
    },
    {
      id: 'lab-r-plt',
      name: 'Platelet Count',
      loinc: '777-3',
      value: 160000,
      unit: '/µL',
      refLow: 150000,
      refHigh: 450000,
      status: 'NORMAL',
      directive: 'Platelets within acceptable range for neuraxial puncture (>70,000 threshold).',
      provenance: {
        documentName: 'Dr_Lal_BLR_Report_44019.pdf',
        page: 1,
        bbox: { ymin: 398, xmin: 68, ymax: 438, xmax: 530 },
        rawOcrText: 'PLATELET COUNT, AUTOMATED ........ 160,000 /uL [150,000 - 450,000] Normal',
        confidence: 0.995,
      },
    },
    {
      id: 'lab-r-wbc',
      name: 'Total Leukocyte Count (TLC)',
      loinc: '6690-2',
      value: 7.4,
      unit: 'x10³/µL',
      refLow: 4.0,
      refHigh: 10.0,
      status: 'NORMAL',
      directive: 'Normal leukocyte count.',
      provenance: {
        documentName: 'Dr_Lal_BLR_Report_44019.pdf',
        page: 1,
        bbox: { ymin: 266, xmin: 68, ymax: 306, xmax: 530 },
        rawOcrText: 'TOTAL LEUCOCYTE COUNT ............ 7.40 x10^3/uL [4.00 - 10.00] Normal',
        confidence: 0.997,
      },
    },
    {
      id: 'lab-r-k',
      name: 'Potassium (Serum K+)',
      loinc: '2823-3',
      value: 4.1,
      unit: 'mEq/L',
      refLow: 3.5,
      refHigh: 5.1,
      status: 'NORMAL',
      directive: 'Electrolyte balance normal.',
      provenance: {
        documentName: 'Dr_Lal_BLR_Report_44019.pdf',
        page: 2,
        bbox: { ymin: 180, xmin: 68, ymax: 220, xmax: 530 },
        rawOcrText: 'POTASSIUM, SERUM (ISE) .......... 4.10 mmol/L [3.50 - 5.10] Normal',
        confidence: 0.996,
      },
    },
    {
      id: 'lab-r-na',
      name: 'Sodium (Serum Na+)',
      loinc: '2951-2',
      value: 137,
      unit: 'mEq/L',
      refLow: 135,
      refHigh: 145,
      status: 'NORMAL',
      directive: 'Normal sodium level.',
      provenance: {
        documentName: 'Dr_Lal_BLR_Report_44019.pdf',
        page: 2,
        bbox: { ymin: 136, xmin: 68, ymax: 176, xmax: 530 },
        rawOcrText: 'SODIUM, SERUM (ISE) ............. 137.0 mmol/L [135.0 - 145.0] Normal',
        confidence: 0.998,
      },
    },
    {
      id: 'lab-r-cl',
      name: 'Chloride (Serum Cl-)',
      loinc: '2075-0',
      value: 101,
      unit: 'mEq/L',
      refLow: 98,
      refHigh: 107,
      status: 'NORMAL',
      directive: 'Normal chloride.',
      provenance: {
        documentName: 'Dr_Lal_BLR_Report_44019.pdf',
        page: 2,
        bbox: { ymin: 224, xmin: 68, ymax: 264, xmax: 530 },
        rawOcrText: 'CHLORIDE, SERUM (ISE) ........... 101.0 mmol/L [98.0 - 107.0] Normal',
        confidence: 0.992,
      },
    },
    {
      id: 'lab-r-hco3',
      name: 'Bicarbonate (HCO3)',
      loinc: '1963-8',
      value: 22,
      unit: 'mEq/L',
      refLow: 22,
      refHigh: 29,
      status: 'NORMAL',
      directive: 'Normal acid base balance.',
      provenance: {
        documentName: 'Dr_Lal_BLR_Report_44019.pdf',
        page: 2,
        bbox: { ymin: 268, xmin: 68, ymax: 308, xmax: 530 },
        rawOcrText: 'BICARBONATE (ENZYMATIC) ......... 22.0 mmol/L [22.0 - 29.0] Normal',
        confidence: 0.988,
      },
    },
    {
      id: 'lab-r-bun',
      name: 'Blood Urea (BUN)',
      loinc: '3094-0',
      value: 21,
      unit: 'mg/dL',
      refLow: 7,
      refHigh: 20,
      status: 'BORDERLINE_HIGH',
      directive: 'Mild pre-renal elevation; ensure adequate IV hydration pre-op.',
      provenance: {
        documentName: 'Dr_Lal_BLR_Report_44019.pdf',
        page: 2,
        bbox: { ymin: 312, xmin: 68, ymax: 352, xmax: 530 },
        rawOcrText: 'BLOOD UREA NITROGEN (BUN) ....... 21.0 mg/dL [7.0 - 20.0] HIGH',
        confidence: 0.994,
      },
    },
    {
      id: 'lab-r-cr',
      name: 'Serum Creatinine',
      loinc: '2160-0',
      value: 1.18,
      unit: 'mg/dL',
      refLow: 0.70,
      refHigh: 1.30,
      status: 'NORMAL',
      directive: 'Baseline renal function preserved (eGFR ~ 68 mL/min).',
      provenance: {
        documentName: 'Dr_Lal_BLR_Report_44019.pdf',
        page: 2,
        bbox: { ymin: 356, xmin: 68, ymax: 396, xmax: 530 },
        rawOcrText: 'CREATININE, SERUM (JAFFE KIN) ... 1.18 mg/dL [0.70 - 1.30] Normal',
        confidence: 0.996,
      },
    },
    {
      id: 'lab-r-glu',
      name: 'Plasma Glucose (Fasting)',
      loinc: '1558-6',
      value: 134,
      unit: 'mg/dL',
      refLow: 70,
      refHigh: 99,
      status: 'BORDERLINE_HIGH',
      directive: 'Elevated fasting glucose; monitor POC capillary glucose every 2h intra-op.',
      provenance: {
        documentName: 'Dr_Lal_BLR_Report_44019.pdf',
        page: 2,
        bbox: { ymin: 400, xmin: 68, ymax: 440, xmax: 530 },
        rawOcrText: 'GLUCOSE FASTING (GOD-POD) ....... 134.0 mg/dL [70.0 - 99.0] HIGH',
        confidence: 0.991,
      },
    },
    {
      id: 'lab-r-inr',
      name: 'Prothrombin Time & INR',
      loinc: '6301-6',
      value: 1.10,
      unit: 'ratio',
      refLow: 0.85,
      refHigh: 1.15,
      status: 'NORMAL',
      directive: 'Coagulation screen normal, but DOAC drug level not reflected by standard INR.',
      provenance: {
        documentName: 'Dr_Lal_BLR_Report_44019.pdf',
        page: 2,
        bbox: { ymin: 480, xmin: 68, ymax: 520, xmax: 530 },
        rawOcrText: 'PT / INR (Electromechanical) .... 1.10 ratio [0.85 - 1.15] Normal',
        confidence: 0.998,
      },
    },
  ],
  overallStatus: 'RED_HARD_STOP',
  primaryActionDirective: 'HARD STOP: Active Apixaban (Eliquis) hold violation for Spinal Anesthesia (28h < 72h required). Delayed Case.',
};

export const PATIENT_AISHA: PatientCase = {
  id: 'PAT-DXB-2026-0319',
  mrn: 'DHA-319022-AE',
  name: 'Aisha Al-Nuaimi',
  age: 32,
  gender: 'F',
  weightKg: 62.0,
  heightCm: 168,
  bmi: 22.0,
  scheduledTimeIso: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
  procedureName: 'Diagnostic Knee Arthroscopy & Meniscal Repair',
  cptCode: 'CPT 29881',
  invasivenessTier: 2,
  facility: 'Medsol Day Surgery Center, Jumeirah, Dubai',
  surgeon: 'Dr. Sarah Jenkins, FRCS Orth',
  anesthesiologist: 'Dr. Tariq Mansoor, MD (Consultant Anaesthetist)',
  asaStatus: 'ASA I',
  rcriClass: 'Class I (<0.4%)',
  stopBangScore: 0,
  swimLane: 'LANE_1_VIRTUAL',
  phoneNumber: '+971 50 319 0221',
  preferredLanguage: 'en',
  isPregnant: false,
  hasActiveInfection: false,
  airway: {
    mallampati: 'Class I',
    mouthOpeningCm: 5.2,
    thyromentalDistanceCm: 7.2,
    neckMobility: 'Full',
    dentition: 'Intact',
    riskTier: 'LOW',
  },
  medications: [],
  allergies: [
    {
      id: 'all-aisha-1',
      allergen: 'No Known Drug Allergies (NKDA)',
      reaction: 'None',
      severity: 'MILD',
      category: 'MEDICATION',
      documentedDate: '2026-08-15',
    },
  ],
  vitals: [
    {
      timestamp: new Date().toISOString(),
      systolicBp: 116,
      diastolicBp: 74,
      heartRate: 66,
      spo2: 100,
      temperatureC: 36.6,
      respiratoryRate: 12,
    },
  ],
  labs: [
    {
      id: 'lab-a-hb',
      name: 'Hemoglobin (Hgb)',
      loinc: '718-7',
      value: 13.8,
      unit: 'g/dL',
      refLow: 12.0,
      refHigh: 15.5,
      status: 'NORMAL',
      directive: 'Hemoglobin within female reference range. Adequate red cell reserve.',
      provenance: {
        documentName: 'Medsol_Lab_Report_31902.pdf',
        page: 1,
        bbox: { ymin: 150, xmin: 68, ymax: 190, xmax: 530 },
        rawOcrText: 'HEMOGLOBIN (SLS Method) ......... 13.8 g/dL [12.0 - 15.5] Normal',
        confidence: 0.999,
      },
    },
    {
      id: 'lab-a-k',
      name: 'Potassium (Serum)',
      loinc: '2823-3',
      value: 4.2,
      unit: 'mEq/L',
      refLow: 3.5,
      refHigh: 5.0,
      status: 'NORMAL',
      directive: 'Normal potassium level. Proceed with standard perioperative fluid management.',
      provenance: {
        documentName: 'Medsol_Lab_Report_31902.pdf',
        page: 1,
        bbox: { ymin: 210, xmin: 68, ymax: 250, xmax: 530 },
        rawOcrText: 'POTASSIUM (ISE Direct) .......... 4.2 mEq/L [3.5 - 5.0] Normal',
        confidence: 0.998,
      },
    },
    {
      id: 'lab-a-cr',
      name: 'Creatinine (Serum)',
      loinc: '2160-0',
      value: 0.8,
      unit: 'mg/dL',
      refLow: 0.5,
      refHigh: 1.1,
      status: 'NORMAL',
      directive: 'Normal renal clearance (eGFR >90 mL/min). Standard perioperative management.',
      provenance: {
        documentName: 'Medsol_Lab_Report_31902.pdf',
        page: 1,
        bbox: { ymin: 270, xmin: 68, ymax: 310, xmax: 530 },
        rawOcrText: 'CREATININE (Enzymatic) .......... 0.8 mg/dL [0.5 - 1.1] Normal',
        confidence: 0.997,
      },
    },
    {
      id: 'lab-a-inr',
      name: 'Coagulation INR',
      loinc: '6301-6',
      value: 1.02,
      unit: 'ratio',
      refLow: 0.85,
      refHigh: 1.15,
      status: 'NORMAL',
      directive: 'Normal baseline coagulation profile. Low surgical bleeding risk.',
      provenance: {
        documentName: 'Medsol_Lab_Report_31902.pdf',
        page: 1,
        bbox: { ymin: 330, xmin: 68, ymax: 370, xmax: 530 },
        rawOcrText: 'INR (Coagulometric) ............. 1.02 ratio [0.85 - 1.15] Normal',
        confidence: 0.999,
      },
    },
    {
      id: 'lab-a-plt',
      name: 'Platelet Count',
      loinc: '777-3',
      value: 265000,
      unit: '10^3/µL',
      refLow: 150000,
      refHigh: 450000,
      status: 'NORMAL',
      directive: 'Platelet count within acceptable range for all anesthetic techniques.',
      provenance: {
        documentName: 'Medsol_Lab_Report_31902.pdf',
        page: 1,
        bbox: { ymin: 390, xmin: 68, ymax: 430, xmax: 530 },
        rawOcrText: 'PLATELET COUNT .................. 265 10^3/uL [150 - 450] Normal',
        confidence: 0.999,
      },
    },
  ],
  overallStatus: 'GREEN_CLEARED',
  primaryActionDirective: 'CLEARED FOR SURGERY: All biomarkers, airway exam, and physiological parameters within safe day-surgery thresholds.',
};

export const PATIENT_JOHN: PatientCase = {
  id: 'PAT-DXB-2026-0105',
  mrn: 'DHA-105820-AE',
  name: 'John Doe',
  age: 42,
  gender: 'M',
  weightKg: 78.0,
  heightCm: 178,
  bmi: 24.6,
  scheduledTimeIso: new Date(Date.now() + 36 * 3600 * 1000).toISOString(),
  procedureName: 'Laparoscopic Inguinal Hernia Repair',
  cptCode: 'CPT 49505',
  invasivenessTier: 2,
  facility: 'Prime Day Surgery Hospital, Al Garhoud, Dubai',
  surgeon: 'Dr. John Henderson, MD FRCS',
  anesthesiologist: 'Dr. Sarah Chen, MD (Chief Anesthesiologist)',
  asaStatus: 'ASA I',
  rcriClass: 'Class I (<0.4%)',
  stopBangScore: 1,
  swimLane: 'LANE_1_VIRTUAL',
  phoneNumber: '+971 50 105 8200',
  preferredLanguage: 'en',
  isPregnant: false,
  hasActiveInfection: false,
  airway: {
    mallampati: 'Class I',
    mouthOpeningCm: 5.0,
    thyromentalDistanceCm: 7.0,
    neckMobility: 'Full',
    dentition: 'Intact',
    riskTier: 'LOW',
  },
  medications: [],
  allergies: [],
  vitals: [
    {
      timestamp: new Date().toISOString(),
      systolicBp: 120,
      diastolicBp: 80,
      heartRate: 70,
      spo2: 99,
      temperatureC: 36.8,
      respiratoryRate: 14,
    },
  ],
  labs: [
    {
      id: 'lab-j-hb',
      name: 'Hemoglobin (Hgb)',
      loinc: '718-7',
      value: 14.5,
      unit: 'g/dL',
      refLow: 13.0,
      refHigh: 17.0,
      status: 'NORMAL',
      directive: 'Normal hemoglobin levels.',
      provenance: {
        documentName: 'Prime_Lab_Report_10582.pdf',
        page: 1,
        bbox: { ymin: 150, xmin: 68, ymax: 190, xmax: 530 },
        rawOcrText: 'HEMOGLOBIN .................... 14.5 g/dL [13.0 - 17.0] Normal',
        confidence: 0.999,
      },
    },
    {
      id: 'lab-j-k',
      name: 'Potassium (Serum)',
      loinc: '2823-3',
      value: 4.3,
      unit: 'mEq/L',
      refLow: 3.5,
      refHigh: 5.0,
      status: 'NORMAL',
      directive: 'Normal potassium.',
      provenance: {
        documentName: 'Prime_Lab_Report_10582.pdf',
        page: 1,
        bbox: { ymin: 210, xmin: 68, ymax: 250, xmax: 530 },
        rawOcrText: 'POTASSIUM ..................... 4.3 mEq/L [3.5 - 5.0] Normal',
        confidence: 0.998,
      },
    },
    {
      id: 'lab-j-plt',
      name: 'Platelet Count',
      loinc: '777-3',
      value: 280000,
      unit: '10^3/µL',
      refLow: 150000,
      refHigh: 450000,
      status: 'NORMAL',
      directive: 'Normal platelet count.',
      provenance: {
        documentName: 'Prime_Lab_Report_10582.pdf',
        page: 1,
        bbox: { ymin: 390, xmin: 68, ymax: 430, xmax: 530 },
        rawOcrText: 'PLATELET COUNT ................ 280 10^3/uL [150 - 450] Normal',
        confidence: 0.999,
      },
    },
  ],
  overallStatus: 'GREEN_CLEARED',
  primaryActionDirective: 'CLEARED FOR SURGERY: Baseline vitals, airway exam, and biomarkers within normal thresholds.',
};

export const MOCK_PATIENT_LIST: PatientCase[] = [
  PATIENT_AISHA,
  PATIENT_FATIMA,
  PATIENT_RAJESH,
  PATIENT_JOHN,
];


